<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Import External Customer</title>

</head>
<style>
.up-btn{
    background-color: #eb5202;
    padding: 0.5%;
    border-color: #eb5202;
    color: white;
    text-shadow:1px 1px 0 rgba(0,0,0,.25);
}
.div-indent{
    padding-left:10px;
    padding-bottom:10px;
    border-bottom:solid 1px lightgrey;
    margin-bottom:40px;
}
.padding-top{
    padding-top:10px;
}
.padding-bottom{
    padding-top:20px;
}
</style>
<body>
    <div>
        
        <div class="div-indent padding-bottom">
            <a href="<?php echo $block->getUrl('shippingrules/Import/importexternalcustomer'); ?>" class="up-btn">Import Customer</a>
            
        </div>

    </div>
</body>

</html>